import { describe,it,expect,vi } from 'vitest'
import { WikimediaMediaProvider,imageSignature } from './wikimedia.js'
import { MediaService,mediaCacheKey,type MediaRepository } from './service.js'
import type { MediaTarget,MediaResult } from './types.js'
import type { PlaceSnapshot } from '../places/service.js'
const target:MediaTarget={hint:{activityId:'a',name:'Meiji Shrine',aliases:[],city:'Tokyo',countryCode:'JP',sourceUrls:['https://en.wikipedia.org/wiki/Meiji_Shrine']}}
const bytes=Buffer.from([255,216,255,0,0,0,0,0,0,0,0,0,0])
const page={title:'Meiji Shrine',pageimage:'Meiji Shrine.jpg',fullurl:'https://en.wikipedia.org/wiki/Meiji_Shrine',coordinates:[{lat:35.676,lon:139.699,globe:'earth'}]}
const info={mime:'image/jpeg',thumburl:'https://upload.wikimedia.org/wikipedia/commons/a/a1/photo.jpg',thumbwidth:960,thumbheight:640,descriptionurl:'https://commons.wikimedia.org/wiki/File:Meiji_Shrine.jpg',extmetadata:{Artist:{value:'Photographer'},LicenseShortName:{value:'CC BY-SA 4.0'},LicenseUrl:{value:'https://creativecommons.org/licenses/by-sa/4.0/'}}}
const json=(data:unknown)=>Buffer.from(JSON.stringify(data))
function provider(p:any=page,i:any=info,image=bytes){const read=vi.fn(async(_url:string,kind:string)=>kind==='image'?image:json(_url.includes('commons.wikimedia')?{query:{pages:[{imageinfo:[i]}]}}:{query:{pages:Array.isArray(p)?p:[p]}}));return{provider:new WikimediaMediaProvider(read),read}}
describe('Wikimedia exact entity media',()=>{
 it('uses actual API URL and preserves license, author and activity-only association',async()=>{const p=provider(),r=await p.provider.search(target,new AbortController().signal);expect(r.status).toBe('ready');expect(r.photos[0]?.source.author).toBe('Photographer');expect(r.photos[0]?.src).toBe(info.thumburl);expect(r.photos[0]?.placeId).toBeUndefined();expect(r.photos[0]?.association).toBe('source_activity');expect(p.read).toHaveBeenCalledTimes(3)})
 it('rejects ambiguity without an HTTP request',async()=>{const p=provider();expect((await p.provider.search({...target,blocked:true},new AbortController().signal)).status).toBe('empty');expect(p.read).not.toHaveBeenCalled()})
 it('does not search generic food, city or unbound names',async()=>{const p=provider();expect((await p.provider.search({hint:{...target.hint,name:'street food',sourceUrls:[]}},new AbortController().signal)).status).toBe('empty');expect(p.read).not.toHaveBeenCalled()})
 it('rejects disambiguation, multiple entities and missing pages',async()=>{for(const pages of [{...page,pageprops:{disambiguation:''}},[page,page],{missing:true}])expect((await provider(pages).provider.search(target,new AbortController().signal)).status).toBe('empty')})
 it('rejects missing licenses, unsupported licenses and restricted images',async()=>{for(const bad of [{...info,extmetadata:{}},{...info,extmetadata:{...info.extmetadata,LicenseShortName:{value:'Fair use'}}},{...info,extmetadata:{...info.extmetadata,Restrictions:{value:'restricted'}}}])expect((await provider(page,bad).provider.search(target,new AbortController().signal)).status).toBe('empty')})
 it('rejects HTML bytes even behind image MIME',async()=>{expect(imageSignature(Buffer.from('<html>not a photo</html>'))).toBe(false);expect((await provider(page,info,Buffer.from('<html>not a photo</html>')).provider.search(target,new AbortController().signal)).reason).toBe('invalid_image_bytes')})
 it('rejects untrusted image hosts',async()=>{expect((await provider(page,{...info,thumburl:'http://127.0.0.1/admin'}).provider.search(target,new AbortController().signal)).status).toBe('empty')})
})
describe('media completion isolation',()=>{
 function setup(){let current='v1';const cache=new Map<string,MediaResult>(),saved=new Map<string,MediaResult>();const snapshot={ownerId:'u',artifact:{id:'g'},contentVersion:'v1',hints:[target.hint]} as PlaceSnapshot
 const repo:MediaRepository={snapshot:async(owner,id)=>{if(owner!=='u'||id!=='g')throw Error('owner');return{...snapshot,contentVersion:current}},targets:async()=>[target,{...target,hint:{...target.hint,activityId:'b'}}],read:async s=>({contentVersion:s.contentVersion,activities:Object.fromEntries([...saved].map(([id,r])=>[id,{media:r.photos[0]?{...r.photos[0],candidates:[]}:null,mediaStatus:r.status}]))}),cached:async k=>cache.get(k),cache:async(k,v)=>{cache.set(k,v)},save:async(s,id,r,signal)=>{signal.throwIfAborted();if(s.contentVersion!==current)throw Error('stale');saved.set(id,r)}}
 const p=provider(),service=new MediaService(repo,p.provider);return{repo,p,service,cache,saved,setVersion:(v:string)=>{current=v}}}
 it('deduplicates identical activity sources, persists and reads without provider work',async()=>{const x=setup();await x.service.resolve('u','g','v1',new AbortController().signal);expect(x.p.read).toHaveBeenCalledTimes(3);expect(x.saved.size).toBe(2);await x.service.read('u','g');await x.service.resolve('u','g','v1',new AbortController().signal);expect(x.p.read).toHaveBeenCalledTimes(3)})
 it('rejects wrong owner and content version before calls',async()=>{const x=setup();await expect(x.service.resolve('other','g','v1',new AbortController().signal)).rejects.toThrow();await expect(x.service.resolve('u','g','old',new AbortController().signal)).rejects.toThrow();expect(x.p.read).not.toHaveBeenCalled()})
 it('rejects a late result after content changes',async()=>{const x=setup();x.p.read.mockImplementationOnce(async()=>{x.setVersion('v2');return json({query:{pages:[page]}})});await expect(x.service.resolve('u','g','v1',new AbortController().signal)).rejects.toThrow('stale');expect(x.saved.size).toBe(0)})
 it('caches provider failures and keeps GET read-only',async()=>{const x=setup();x.p.read.mockRejectedValue(Error('slow/bad link'));await x.service.resolve('u','g','v1',new AbortController().signal);await x.service.resolve('u','g','v1',new AbortController().signal);expect(x.p.read).toHaveBeenCalledTimes(1);expect([...x.saved.values()][0]?.status).toBe('unavailable')})
 it('same resolved place is reused across activities and translated names',()=>{const place={placeId:'osm:way:1'} as any;expect(mediaCacheKey({...target,place})).toBe(mediaCacheKey({place,hint:{...target.hint,name:'明治神宮',activityId:'b'}}))})
})
