import type {
  ChatMessage,
  ChatOptions,
  OpenRouterClient
} from '../providers/openrouter/client.js'
import { DESTINATION_PROFILES, type DestinationRecommendation } from '../destinations/catalog.js'
import type { RoutePick } from '../route-plans/engine.js'
import type { TripState, ConversationMessage } from './schema.js'
import type { BilingualText } from './types.js'
import type { RuleParseResult } from './rules.js'
import { parseBudget } from './budget.js'
import { canonicalDestinationIata, isSupportedDestinationIata, isSupportedOrigin } from './catalog-adapter.js'

export interface ConversationLlmResult {
  state: TripState
  reply?: BilingualText
  source: 'llm' | 'rules'
  warnings: string[]
}

type UnknownRecord = Record<string, unknown>

function isRecord(value: unknown): value is UnknownRecord {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function extractJson(content: string): UnknownRecord {
  const fenced = content.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]
  const raw = fenced ?? content
  const start = raw.indexOf('{')
  const end = raw.lastIndexOf('}')
  if (start < 0 || end <= start) throw new Error('invalid conversation response')
  const parsed: unknown = JSON.parse(raw.slice(start, end + 1))
  if (!isRecord(parsed)) throw new Error('invalid conversation response')
  return parsed
}

function assistantContent(response: Record<string, unknown>): string {
  const choices = response.choices
  if (!Array.isArray(choices) || choices.length === 0 || !isRecord(choices[0])) throw new Error('empty conversation response')
  const message = choices[0].message
  if (!isRecord(message) || typeof message.content !== 'string') throw new Error('empty conversation response')
  return message.content
}

function buildPrompt(today: string): string {
  return [
    'You are FlightOR, a bilingual travel requirement extractor.',
    `Today is ${today}. Extract only facts expressed by the user messages; never invent a city, IATA, date, budget, fare, flight, visa rule, or availability.`,
    'Recommendations and routes are generated by server code. Never generate them in this response.',
    'A country or region is not a city. Keep required_iatas empty when the user has not named a city or airport.',
    'Return one JSON object and no markdown. Use only these keys:',
    '{"reply":{"zh":"short Chinese reply","en":"short English reply"},"delta":{"origin":"PEK|null","window_from":"YYYY-MM-DD|null","window_to":"YYYY-MM-DD|null","travel_days":7,"budget_max":20000,"interests":["culture"],"regions":["japan"],"required_iatas":["NRT"],"excluded_iatas":[],"destination_mode":"explicit|recommend","pace":"relaxed|balanced|many_cities","priorities":["budget"]}}',
    'Omit unknown fields. The delta is advisory and will be checked against exact user-text evidence by the server. Keep each reply concise and ask no more than one question.'
  ].join('\n')
}

function value(root: UnknownRecord, key: string): unknown {
  const delta = root.delta
  if (isRecord(delta) && key in delta) return delta[key]
  const state = root.state
  if (isRecord(state) && key in state) return state[key]
  return root[key]
}

function asString(valueToRead: unknown): string | undefined {
  if (typeof valueToRead !== 'string') return undefined
  const result = valueToRead.trim()
  return result || undefined
}

function asIata(valueToRead: unknown): string | undefined {
  const result = asString(valueToRead)?.toUpperCase()
  return result && /^[A-Z]{3}$/.test(result) ? result : undefined
}

function asDate(valueToRead: unknown): string | undefined {
  if (typeof valueToRead !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(valueToRead)) return undefined
  const timestamp = Date.parse(`${valueToRead}T00:00:00Z`)
  return Number.isFinite(timestamp) && new Date(timestamp).toISOString().slice(0, 10) === valueToRead ? valueToRead : undefined
}

function asPositiveInt(valueToRead: unknown, maximum: number): number | undefined {
  const valueNumber = typeof valueToRead === 'number'
    ? valueToRead
    : typeof valueToRead === 'string' && /^\d+$/.test(valueToRead.trim())
      ? Number(valueToRead)
      : NaN
  return Number.isInteger(valueNumber) && valueNumber >= 1 && valueNumber <= maximum ? valueNumber : undefined
}

function stringArray(valueToRead: unknown): string[] {
  if (!Array.isArray(valueToRead)) return []
  return [...new Set(valueToRead.flatMap(item => {
    const result = asString(item)
    return result ? [result] : []
  }))]
}

function textHasDate(text: string, date: string): boolean {
  if (text.includes(date)) return true
  const month = Number(date.slice(5, 7))
  const day = Number(date.slice(8, 10))
  return new RegExp(`${month}\\s*月\\s*${day}\\s*[日号]?`).test(text)
}

function textHasDays(text: string, days: number): boolean {
  if (new RegExp(`(?:^|[^\\d])${days}\\s*天`).test(text)) return true
  return days === 7 && /一周|一个星期|一星期|一礼拜|one\s+week/i.test(text)
}

function textHasBudget(text: string, amount: number): boolean {
  if (!/预算|budget|元|块|万|千|[kKwW]/i.test(text)) return false
  const wan = amount / 10_000
  const qian = amount / 1_000
  const escapedAmount = String(amount).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const escapedWan = String(wan).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const escapedQian = String(qian).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`(?:预算|budget)[^\\d]{0,8}${escapedAmount}(?:\\s*(?:元|块|rmb|cny))?`, 'i').test(text)
    || new RegExp(`${escapedWan}\\s*[万w]`, 'i').test(text)
    || new RegExp(`${escapedQian}\\s*[千k]`, 'i').test(text)
}

function textHasInterest(text: string, interest: string): boolean {
  const patterns: Record<string, RegExp> = {
    culture: /文化|历史|古迹|博物馆|艺术|culture|history|museum|art/i,
    food: /美食|吃|餐厅|food|cuisine/i,
    nature: /自然|风景|山|海边|徒步|nature|beach|hiking/i,
    shopping: /购物|买|shopping/i,
    nightlife: /夜生活|酒吧|nightlife|bar\b/i,
    onsen: /温泉|onsen/i,
    anime: /动漫|二次元|anime/i,
    family: /亲子|family/i,
    beach: /海岛|island/i
  }
  return patterns[interest]?.test(text) ?? false
}

function textHasRegion(text: string, region: string): boolean {
  const patterns: Record<string, RegExp> = {
    japan: /日本|japan/i,
    schengen: /欧洲|欧盟|申根|欧洲大陆|europe|schengen/i,
    visa_free: /东南亚|东亚|免签|落地签|southeast\s+asia|visa[- ]free/i
  }
  return patterns[region]?.test(text) ?? false
}

function validReply(root: UnknownRecord): BilingualText | undefined {
  if (!isRecord(root.reply)) return undefined
  const zh = asString(root.reply.zh)
  const en = asString(root.reply.en)
  if (!zh || !en || zh.length > 240 || en.length > 480) return undefined
  return { zh, en }
}

/**
 * Keep model extraction evidence-bound.  In particular, a model-generated
 * `NRT` is rejected unless the latest user turn actually mentioned Tokyo,
 * Narita or NRT (the rule parser has already resolved that evidence).
 */
function groundModelDelta(root: UnknownRecord, base: TripState, latestText: string, latestRule: RuleParseResult): Partial<TripState> {
  const result: Partial<TripState> = {}
  const origin = asIata(value(root, 'origin'))
  if (origin && isSupportedOrigin(origin) && latestRule.evidenceIatas.has(origin)) result.origin = origin

  const windowFrom = asDate(value(root, 'window_from'))
  const windowTo = asDate(value(root, 'window_to'))
  if (windowFrom && textHasDate(latestText, windowFrom)) {
    result.window_from = windowFrom
    if (windowTo && windowTo >= windowFrom && textHasDate(latestText, windowTo)) result.window_to = windowTo
  }

  const travelDays = asPositiveInt(value(root, 'travel_days'), 60)
  if (travelDays !== undefined && textHasDays(latestText, travelDays)) result.travel_days = travelDays
  const budget = asPositiveInt(value(root, 'budget_max'), 100_000_000)
  const ruleBudget = parseBudget(latestText)
  // A deterministic amount parsed from the same turn is authoritative.  A
  // coarser model value (for example 10,000 for “一万五”) must not replace it.
  const budgetHasEvidence = budget !== undefined && (
    ruleBudget !== null ? ruleBudget === budget : textHasBudget(latestText, budget)
  )
  if (budgetHasEvidence) result.budget_max = budget

  const interestAliases: Record<string, string> = {
    onsen: 'nature',
    anime: 'culture',
    family: 'nature',
    beach: 'nature'
  }
  const interests = stringArray(value(root, 'interests'))
    .map(interest => interestAliases[interest] ?? interest)
    .filter(interest => ['culture', 'food', 'nature', 'shopping', 'nightlife'].includes(interest))
    .filter(interest => textHasInterest(latestText, interest))
  if (interests.length > 0) result.interests = interests as TripState['interests']
  const regionAliases: Record<string, string> = {
    southeast_asia: 'visa_free',
    east_asia: 'visa_free',
    korea: 'visa_free',
    visa_free: 'visa_free'
  }
  const regions = stringArray(value(root, 'regions'))
    .map(region => regionAliases[region] ?? region)
    .filter(region => ['japan', 'schengen', 'visa_free'].includes(region))
    .filter(region => latestRule.evidenceRegions.has(region as import('../destinations/catalog.js').DestinationRegion) || textHasRegion(latestText, region))
  if (regions.length > 0) result.regions = regions as TripState['regions']

  const required = stringArray(value(root, 'required_iatas')).map(asIata).filter((iata): iata is string => {
    return iata !== undefined && isSupportedDestinationIata(iata) && latestRule.evidenceIatas.has(iata)
  })
  const modelDestination = asIata(value(root, 'destination'))
  if (modelDestination && isSupportedDestinationIata(modelDestination) && latestRule.evidenceIatas.has(modelDestination)) required.push(modelDestination)
  if (required.length > 0) result.required_iatas = [...new Set(required)]
  const excluded = stringArray(value(root, 'excluded_iatas')).map(asIata).filter((iata): iata is string => {
    return iata !== undefined && isSupportedDestinationIata(iata) && latestRule.evidenceIatas.has(iata)
  })
  if (excluded.length > 0) result.excluded_iatas = [...new Set(excluded)]

  const mode = asString(value(root, 'destination_mode'))
  // The deterministic parser owns mode transitions.  This keeps a model
  // from undoing recommendation authorization when the user merely adds a
  // named must-visit city, while still accepting an evidence-backed opt-out.
  if (mode === 'recommend' && latestRule.state.destination_mode === 'recommend') result.destination_mode = 'recommend'
  if (mode === 'explicit' && latestRule.state.destination_mode === 'explicit') result.destination_mode = 'explicit'
  const pace = asString(value(root, 'pace'))
  if ((pace === 'relaxed' || pace === 'balanced' || pace === 'many_cities') && latestRule.state.pace === pace) result.pace = pace
  const priorities = stringArray(value(root, 'priorities')).filter(priority => ['budget', 'comfort', 'few_transfers', 'culture'].includes(priority))
    .filter(priority => latestRule.state.priorities.includes(priority as never))
  if (priorities.length > 0) result.priorities = priorities as TripState['priorities']

  // Avoid an unused-base warning while documenting that the base is supplied
  // for future field-level evidence checks and state shape review.
  void base
  return result
}

function mergeGrounded(base: TripState, model: Partial<TripState>): TripState {
  const result: TripState = {
    ...base,
    interests: [...base.interests],
    regions: [...base.regions],
    required_iatas: [...base.required_iatas],
    excluded_iatas: [...base.excluded_iatas],
    priorities: [...base.priorities]
  }
  if (model.origin) result.origin = model.origin
  if (model.window_from) result.window_from = model.window_from
  if (model.window_to) result.window_to = model.window_to
  if (model.travel_days) result.travel_days = model.travel_days
  if (model.budget_max) result.budget_max = model.budget_max
  if (model.interests) result.interests = [...new Set([...result.interests, ...model.interests])]
  if (model.regions) result.regions = [...new Set([...result.regions, ...model.regions])]
  if (model.required_iatas) result.required_iatas = [...new Set([...result.required_iatas, ...model.required_iatas])]
  if (model.excluded_iatas) result.excluded_iatas = [...new Set([...result.excluded_iatas, ...model.excluded_iatas])]
  if (model.destination_mode) result.destination_mode = model.destination_mode
  if (model.pace) result.pace = model.pace
  if (model.priorities) result.priorities = [...new Set([...result.priorities, ...model.priorities])]
  const excludedCanonical = new Set(result.excluded_iatas.map(canonicalDestinationIata))
  result.required_iatas = result.required_iatas.filter(iata => !excludedCanonical.has(canonicalDestinationIata(iata)))
  return result
}

function latestUser(messages: ConversationMessage[]): ConversationMessage | undefined {
  return [...messages].reverse().find(message => message.role === 'user')
}

export async function enrichWithLlm(
  client: Pick<OpenRouterClient, 'chat'> | undefined,
  messages: ConversationMessage[],
  base: TripState,
  latestRule: RuleParseResult,
  today: string
): Promise<ConversationLlmResult> {
  if (!client) return { state: base, source: 'rules', warnings: ['llm_fallback'] }
  const latest = latestUser(messages)
  const latestText = latest?.content ?? ''
  const promptMessages: ChatMessage[] = [
    { role: 'system', content: buildPrompt(today) },
    { role: 'system', content: `Current client state: ${JSON.stringify(base)}` },
    ...messages.slice(-12).map(message => ({ role: message.role, content: message.content.slice(0, 1_000) }))
  ]
  const options: ChatOptions = {
    maxTokens: 900,
    temperature: 0,
    reasoning: { effort: 'none', exclude: true }
  }
  try {
    const response = await client.chat(promptMessages, undefined, options)
    const payload = extractJson(assistantContent(response))
    const model = groundModelDelta(payload, base, latestText, latestRule)
    const result: ConversationLlmResult = {
      state: mergeGrounded(base, model),
      source: 'llm',
      warnings: []
    }
    const reply = validReply(payload)
    if (reply) result.reply = reply
    return result
  } catch {
    return { state: base, source: 'rules', warnings: ['llm_fallback'] }
  }
}

interface ReplySynthesisInput {
  state: TripState
  recommendations: readonly DestinationRecommendation[]
  routes: readonly RoutePick[]
  missing: readonly string[]
}

function routeCodes(routes: readonly RoutePick[]): string[] {
  const codes: string[] = []
  for (const pick of routes) {
    for (const code of pick.route?.cities ?? []) {
      if (typeof code === 'string' && /^[A-Z]{3}$/.test(code)) codes.push(code)
    }
    for (const code of pick.route?.citySeq ?? []) {
      if (typeof code === 'string' && /^[A-Z]{3}$/.test(code)) codes.push(code)
    }
  }
  return [...new Set(codes)]
}

function replyAllowedIatas(input: ReplySynthesisInput): Set<string> {
  const allowed = new Set<string>([
    ...input.state.required_iatas,
    ...input.recommendations.map(item => item.iata),
    ...routeCodes(input.routes)
  ])
  // The origin is a verified server-supported airport too.  It is not a
  // destination recommendation, but allowing it prevents a grounded reply
  // from being rejected merely because it says “from Beijing”.
  if (input.state.origin && /^[A-Z]{3}$/.test(input.state.origin)) allowed.add(input.state.origin)
  return allowed
}

function canonicalForReply(value: string): string {
  const profile = DESTINATION_PROFILES.find(item => item.iata === value)
  return profile?.canonicalIata ?? value
}

function containsUnverifiedCatalogCity(text: string, allowedIatas: Set<string>): boolean {
  const allowedCanonical = new Set([...allowedIatas].map(canonicalForReply))
  return DESTINATION_PROFILES.some(profile => {
    const cityEn = new RegExp(`(?:^|[^A-Za-z])${profile.cityEn.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}(?=$|[^A-Za-z])`, 'i')
    const code = new RegExp(`(?:^|[^A-Za-z0-9])${profile.iata}(?=$|[^A-Za-z0-9])`, 'i')
    const mentioned = text.includes(profile.cityZh) || cityEn.test(text) || code.test(text)
    return mentioned && !allowedCanonical.has(canonicalForReply(profile.iata))
  })
}

function groundedReply(root: UnknownRecord, input: ReplySynthesisInput): BilingualText | undefined {
  const reply = validReply(root)
  if (!reply) return undefined
  const questionMarks = (reply.zh.match(/[？?]/g)?.length ?? 0) + (reply.en.match(/[？?]/g)?.length ?? 0)
  if (questionMarks > 1) return undefined
  if (containsUnverifiedCatalogCity(`${reply.zh} ${reply.en}`, replyAllowedIatas(input))) return undefined
  return reply
}

function buildSynthesisPrompt(input: ReplySynthesisInput): string {
  const verified = {
    state: {
      origin: input.state.origin,
      window_from: input.state.window_from,
      window_to: input.state.window_to,
      travel_days: input.state.travel_days,
      budget_max: input.state.budget_max,
      interests: input.state.interests,
      regions: input.state.regions,
      required_iatas: input.state.required_iatas,
      excluded_iatas: input.state.excluded_iatas,
      destination_mode: input.state.destination_mode,
      pace: input.state.pace,
      priorities: input.state.priorities
    },
    missing: input.missing,
    recommendations: input.recommendations.map(item => ({
      iata: item.iata,
      cityZh: item.cityZh,
      cityEn: item.cityEn,
      region: item.region,
      reason: item.reason,
      suggestedDays: item.suggestedDays
    })),
    routes: input.routes.map(item => ({
      kind: item.kind,
      cities: item.route?.cities ?? [],
      citySeq: item.route?.citySeq ?? []
    }))
  }
  return [
    'You are the final FlightOR reply editor. Return exactly one JSON object: {"reply":{"zh":"...","en":"..."}}.',
    'Use only the verified server summary below. Do not add or rename cities, airports, prices, fares, flights, visa facts, dates, or availability.',
    'Recommendations and routes are already generated by the server; explain them briefly rather than inventing alternatives.',
    'If missing is non-empty, ask at most one concise question for the highest-value missing field. Keep both languages consistent.',
    'Any city you mention must appear in required_iatas, recommendations, or routes. Keep zh <= 240 characters and en <= 480 characters.',
    `Verified server summary: ${JSON.stringify(verified)}`
  ].join('\n')
}

/**
 * Synthesize only the final wording after deterministic server work is done.
 * This deliberately receives no raw user text, so the model cannot turn a
 * conversational suggestion into an unverified route fact.
 */
export async function synthesizeReply(
  client: Pick<OpenRouterClient, 'chat'> | undefined,
  input: ReplySynthesisInput
): Promise<BilingualText | undefined> {
  if (!client) return undefined
  const options: ChatOptions = {
    maxTokens: 320,
    temperature: 0,
    reasoning: { effort: 'none', exclude: true }
  }
  try {
    const response = await client.chat([{ role: 'system', content: buildSynthesisPrompt(input) }], undefined, options)
    return groundedReply(extractJson(assistantContent(response)), input)
  } catch {
    return undefined
  }
}
